apiVersion: v1
kind: Pod
metadata:
  name: myapp-env-conig-pod
spec:
  containers:
  - name: myapp-env
    image: jyang4900/myapp-env
    env:
    - name: hobby
      valueFrom:
        configMapKeyRef:
          name: my-config
          key: hobby-in-config
